version: '3.8'

services:
  postgres:
    container_name: barcodes_container
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=barcodes_psql
    volumes:
      - ./db-init/init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh
      - ./db-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    #command: --init-file /data/application/db.sql
    networks:
      - dockerNet

  pgadmin:
    container_name: pgadmin_container_barcodes
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./db-init/servers.json:/pgadmin4/servers.json
      - ./db-init/pgpass:/pgpass
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5070}:80"
    networks:
      - dockerNet
    depends_on:
      - postgres
    restart: unless-stopped

  dev:
    container_name: barcodes_rest_dev
    image: barcodes-rest-devel:0.0.1
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - pgadmin
    restart: unless-stopped
    networks:
      - dockerNet

#  prod:
#    container_name: barcodes_rest_prod
#    image: barcodes-rest-prod:0.0.1
#    build:
#      context: .
#      target: production
#      dockerfile: ./Dockerfile
#    command: npm run start:prod
#    ports:
#      - 3000:3000
#      - 9229:33601
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    depends_on:
#      - postgres
#    links:
#      - postgres:postgres
#    restart: unless-stopped


networks:
  dockerNet:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  barcodesDevel:



